version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOST: redis
    ports:
      - 8082:8081
    depends_on:
      - redis
